# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3cd9cfbc93cb5ad0414933652b34915ab9c7c4d92fab072d995d815e3b76ad6c0badc3eb2c570fc84800e3fa9fcd8923cb10f30c1987ec387437428f22e15d28

test:
  secret_key_base: 8f8bbfa0452f2c81d7ddfca6ce70e4eb6dd2f6d68bdeddac96754346f35c833cfed884226f7c9cd168618b32ba5b4510aad760880d548bb640b8a70f56026db1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
